zuul:
  add-proxy-headers: true
  host:
    max-per-route-connections: 20
    max-total-connections: 200
  routes:
    users:
      path: "/users/**"
      service-id: user-service
    orders:
      path: "/orders/**"
      service-id: order-service
